name: semo
description: "Semo is designed to offer a seamless movie and TV show streaming experience."
version: 2.4.6+9

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  audio_session: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.1
  diacritic: ^0.1.6
  dio: ^5.9.0
  envied: ^1.2.1
  firebase_analytics: ^12.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_remote_config: ^6.0.1
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^17.2.3
  flutter_settings_ui: ^3.0.1
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.3.1
  google_sign_in: ^7.1.1
  html: ^0.15.6
  infinite_scroll_pagination: ^5.1.1
  internet_connection_checker_plus: ^2.7.2
  logger: ^2.6.1
  lottie: ^3.3.2
  mime: ^1.0.5
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  animated_read_more_text: ^0.0.6
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  universal_back_gesture: ^2.1.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.3.3
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  background_fetch: ^1.1.5
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 23
  remove_alpha_ios: true
  adaptive_icon_background: "#250604"
  adaptive_icon_foreground: "assets/images/app_icon_108.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#250604"
    theme_color: "#AB261D"

flutter_native_splash:
  color: "#250604"
  android_12:
    color: "#250604"

flutter:
  uses-material-design: true
  assets:
    - assets/gen/
    - assets/images/
    - assets/lottie/
